import {Defense,LEVELS,TYPES,ENEMIES,W,H,stats,upgradeCost,wavePlan,onPath,pathData,distance} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d'),typeKeys=Object.keys(TYPES);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let game=new Defense(),screen='campaign',selected=-1,blueprint=null,paused=false,speed=1,clock=0,last=0,uiClock=0,noticeTime=0,effects=[],hover=-1,mapScale=1,mapX=0,mapY=0,viewW=960,viewH=600;
let progress=Array(6).fill(0),sound=false,audio=null;
try{const data=JSON.parse(localStorage.getItem('pristav-defense-progress')||'null');if(Array.isArray(data))progress=progress.map((_,i)=>Math.max(0,Math.min(3,Number(data[i])||0)));sound=localStorage.getItem('pristav-defense-sound')==='true';}catch{}
const money=n=>Math.round(n).toLocaleString('cs-CZ');
function tone(freq=440,duration=.1,volume=.025,type='sine',end){if(!sound||!audio)return;try{const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+duration);o.onended=()=>{o.disconnect();g.disconnect();};}catch{}}
function readyAudio(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch{}}
function syncSound(){$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Vypnout zvuk':'Zapnout zvuk');$('sound').textContent=sound?'♫':'♪';}
$('sound').onclick=()=>{sound=!sound;readyAudio();syncSound();try{localStorage.setItem('pristav-defense-sound',String(sound));}catch{}if(sound)tone(500,.14);};syncSound();
function circle(c,x,y,r,fill,stroke,width=1){c.beginPath();c.arc(x,y,r,0,Math.PI*2);if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
function turret(c,x,y,type,angle=-Math.PI/2,level=1,scale=1){const color=TYPES[type].color;c.save();c.translate(x,y);c.scale(scale,scale);c.shadowColor='#0009';c.shadowBlur=6;c.shadowOffsetY=5;circle(c,0,0,22,'#173941','#5c7a78',2);c.shadowBlur=0;c.shadowOffsetY=0;circle(c,0,0,17,'#09252f',color+'88',1.5);c.save();c.rotate(angle);
 if(type==='cannon'){c.fillStyle='#375752';c.fillRect(-10,-11,20,22);c.strokeStyle=color;c.lineWidth=5;c.beginPath();c.moveTo(0,-4);c.lineTo(31,-4);c.moveTo(0,4);c.lineTo(31,4);c.stroke();circle(c,0,0,6,color);}
 if(type==='tesla'){c.rotate(Math.PI/4);c.fillStyle='#403c60';c.fillRect(-10,-10,20,20);c.strokeStyle=color;c.lineWidth=2;c.strokeRect(-10,-10,20,20);circle(c,0,0,5,color);for(let i=0;i<4;i++){c.rotate(Math.PI/2);c.fillStyle=color;c.fillRect(13,-2,6,4);}}
 if(type==='frost'){c.strokeStyle=color;c.lineWidth=2.5;for(let i=0;i<6;i++){c.rotate(Math.PI/3);c.beginPath();c.moveTo(0,0);c.lineTo(15,0);c.moveTo(10,0);c.lineTo(6,-5);c.moveTo(10,0);c.lineTo(6,5);c.stroke();}circle(c,0,0,4,'#d5faff');}
 if(type==='mortar'){circle(c,0,0,12,'#736453',color,2);c.fillStyle='#968267';c.fillRect(0,-8,19,16);circle(c,20,0,8,color);circle(c,20,0,5,'#1e302f');}
 c.restore();for(let i=0;i<level;i++)circle(c,(i-(level-1)/2)*8,28,2.4,color);c.restore();}
function miniMap(c,index,w,h){const l=LEVELS[index];c.clearRect(0,0,w,h);c.save();c.translate(w*.13,h*.07);c.scale(w*.75/W,h*.84/H);for(const points of l.paths){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.strokeStyle='#a4d6bd77';c.lineWidth=14;c.lineJoin='round';c.stroke();}for(const [x,y]of l.pads)circle(c,x,y,11,'#c1ebca35');circle(c,930,300,23,'#ffd192');c.restore();}
function drawCampaign(){const unlocked=progress.findIndex(n=>n===0);$('total-stars').innerHTML=`${progress.reduce((a,b)=>a+b,0)} <span>/ 18</span>`;$('levels').innerHTML=LEVELS.map((l,i)=>{const open=i===0||progress[i-1]>0;return`<button class="level-card ${i===unlocked?'current':''}" data-level="${i}" ${open?'':'disabled'} aria-label="Sektor ${i+1}, ${l.name}, ${open?progress[i]+' ze 3 hvězd':'uzamčeno'}"><canvas aria-hidden="true" width="660" height="212"></canvas><span class="card-number">0${i+1}</span><span class="card-status">${!open?'UZAMČENO':progress[i]?'DOKONČENO':'VSTOUPIT →'}</span><div class="card-info"><div><h3>${l.name}</h3><p>${l.waves} VLN / ${l.paths.length===1?'JEDNA TRASA':'DVĚ TRASY'}</p></div><span class="card-stars">${'★'.repeat(progress[i])}<span class="empty">${'☆'.repeat(3-progress[i])}</span></span></div></button>`;}).join('');document.querySelectorAll('[data-level]').forEach(b=>{miniMap(b.querySelector('canvas').getContext('2d'),Number(b.dataset.level),660,212);b.onclick=()=>startLevel(Number(b.dataset.level));});}
function showCampaign(){closeModal();screen='campaign';paused=false;$('campaign').classList.remove('hidden');$('battle').classList.add('hidden');drawCampaign();window.scrollTo({top:0,behavior:'instant'});}
function startLevel(index){closeModal();game=new Defense(index);screen='battle';selected=-1;blueprint=null;paused=false;speed=1;effects=[];hover=-1;readyAudio();$('campaign').classList.add('hidden');$('battle').classList.remove('hidden');$('sector-label').textContent=`SEKTOR 0${index+1} / ${game.level.area}`;$('mission-name').textContent=game.level.name;$('speed').textContent='1×';notice('Postav věže. Pak spusť první vlnu.',4);resize();syncUI();canvas.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function notice(text,seconds=2.6,danger=false){$('notice').textContent=text;$('notice').className='notice show'+(danger?' danger':'');noticeTime=seconds;}
function closeModal(){if($('modal').open)$('modal').close();}
function modal(kicker,title,copy,buttons){$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-copy').innerHTML=copy;$('modal-actions').replaceChildren();for(const [text,action,secondary]of buttons){const b=document.createElement('button');b.textContent=text;b.className=secondary?'text-btn':'primary';b.onclick=action;$('modal-actions').append(b);}if(!$('modal').open)$('modal').showModal();}
function resume(){paused=false;closeModal();readyAudio();canvas.focus({preventScroll:true});syncUI();}
function pause(){if(screen!=='battle'||['won','lost'].includes(game.state))return;paused=true;modal('MOTORY NA VOLNOBĚH','Chvíle klidu.',`<p>Obrana počká. Tvoje věže drží pozice.</p>`,[['Pokračovat →',resume],['Začít sektor znovu',()=>startLevel(game.index),true],['Mapa sektorů',showCampaign,true]]);syncUI();}
$('pause').onclick=pause;$('home').onclick=()=>{if(screen==='battle'&&!['won','lost'].includes(game.state))pause();else showCampaign();};
$('help').onclick=()=>{const wasPaused=paused;if(screen==='battle')paused=true;modal('POLNÍ PŘÍRUČKA','Jak udržet přístav.',`<ol class="help-list"><li><b>Vyber věž a místo.</b> Svítící kruhy na mapě jsou stavební plošiny. Stavět i vylepšovat můžeš také během útoku.</li><li><b>Spusť vlnu.</b> Věže míří a střílejí samy. Za potopené lodě získáš kredity.</li><li><b>Kombinuj obranu.</b> Kryo zpomaluje, Tesla ignoruje pancíř, minomet zasahuje celé skupiny.</li><li><b>Vylepšuj.</b> Kliknutím na postavenou věž otevřeš dvě úrovně vylepšení a prodej za 70 % investice.</li><li><b>Udrž maják.</b> Každá proplutá loď ubere životy. Vyhraj sektor a odemkni další; za plných 20 životů dostaneš 3 hvězdy.</li></ol><p>1–4 věž · šipky místo · Enter stavět<br>U vylepšit · mezerník vlna · P pauza</p>`,[['Rozumím →',()=>{closeModal();if(wasPaused)pause();else{paused=false;if(screen==='battle')canvas.focus({preventScroll:true});}syncUI();}]]);};
$('modal').addEventListener('cancel',e=>{e.preventDefault();if(screen==='battle'&&!['won','lost'].includes(game.state))resume();else closeModal();});
function end(won,stars=0){paused=false;blueprint=null;if(won){progress[game.index]=Math.max(progress[game.index],stars);try{localStorage.setItem('pristav-defense-progress',JSON.stringify(progress));}catch{}[440,554,660,880].forEach((f,i)=>setTimeout(()=>tone(f,.4,.06),i*110));}else tone(180,.5,.05,'triangle',55);const final=won&&game.index===5;modal(won?'SEKTOR ZAJIŠTĚN':'OBRANA PROLOMENA',final?'Maják stále svítí.':won?'Přístav drží.':'Příliv byl silnější.',`${won?`<div class="result-stars">${'★'.repeat(stars)}<span style="opacity:.2">${'★'.repeat(3-stars)}</span></div>`:''}<p>${final?'Celá flotila je na dně. Dokončil jsi všech šest sektorů.':won?'Dobrá práce, veliteli. Další sektor čeká.':'Zkus více krya u zatáček a Teslu proti obrněncům.'}</p><div class="result-stats"><div><b>${game.kills}</b><span>POTOPENO</span></div><div><b>${game.lives}/20</b><span>MAJÁK</span></div><div><b>${game.wave}/${game.level.waves}</b><span>VLNY</span></div></div>`,won&&!final?[['Další sektor →',()=>startLevel(game.index+1)],['Zopakovat pro 3 hvězdy',()=>startLevel(game.index),true],['Mapa sektorů',showCampaign,true]]:won?[['Mapa sektorů →',showCampaign],['Zopakovat poslední sektor',()=>startLevel(game.index),true]]:[['Zkusit znovu →',()=>startLevel(game.index)],['Mapa sektorů',showCampaign,true]]);syncUI();}
function makeTowerCards(){$('tower-options').innerHTML=Object.entries(TYPES).map(([type,t],i)=>`<button class="tower-card" data-tower="${type}" style="--accent:${t.color}" aria-label="${t.name}, ${t.cost} kreditů. ${t.desc}"><canvas width="100" height="90" aria-hidden="true"></canvas><span class="tower-cost">${t.cost}</span><strong>${t.name}</strong><small>${t.tag}</small><span class="tower-key">${i+1}</span></button>`).join('');document.querySelectorAll('[data-tower]').forEach(b=>{turret(b.querySelector('canvas').getContext('2d'),46,41,b.dataset.tower,-.55,1,1.25);b.onclick=()=>chooseType(b.dataset.tower);});}
function chooseType(type){if(paused||!['build','wave'].includes(game.state))return;readyAudio();if(selected>=0&&!game.towerAt(selected)){if(game.build(selected,type)){blueprint=null;events();syncUI();canvas.focus({preventScroll:true});return;}notice('Na tuto věž chybí kredity.',2,true);}blueprint=type;selected=-1;syncUI();canvas.focus({preventScroll:true});}
function selectPad(i){if(paused||!['build','wave'].includes(game.state))return;readyAudio();if(blueprint&&!game.towerAt(i)){if(game.build(i,blueprint)){selected=i;blueprint=null;events();}else{selected=i;notice('Nejdřív potřebuješ více kreditů.',2,true);}}else{selected=i;blueprint=null;}syncUI();}
function clearSelection(){selected=-1;blueprint=null;syncUI();}
$('cancel-selection').onclick=clearSelection;
$('upgrade').onclick=()=>{if(paused)return;if(game.upgrade(selected)){tone(660,.17,.045);events();syncUI();}else notice('Na vylepšení chybí kredity.',2,true);};
$('sell').onclick=()=>{if(paused)return;if(game.sell(selected)){tone(290,.12);clearSelection();}};
$('send-wave').onclick=()=>{if(paused)return;readyAudio();if(!game.towers.length){notice('Nejdřív postav alespoň jednu věž.',2.5,true);return;}if(game.startWave()){events();syncUI();canvas.focus({preventScroll:true});}};
$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';$('speed').setAttribute('aria-label',`Rychlost ${speed}×. Přepnout rychlost.`);};
function syncUI(){if(screen!=='battle')return;$('money').textContent=money(game.money);$('lives').innerHTML=`${game.lives} <small>/ 20</small>`;$('lives').classList.toggle('low-health',game.lives<8);$('wave').innerHTML=`${game.wave} <small>/ ${game.level.waves}</small>`;$('board-state').textContent=paused?'POZASTAVENO':game.state==='wave'?'FLOTILA NA DOHLED':game.state==='build'?'PŘÍPRAVA OBRANY':game.state==='won'?'SEKTOR ZAJIŠTĚN':'OBRANA PROLOMENA';$('send-wave').disabled=game.state!=='build'||paused;$('send-wave').innerHTML=game.state==='wave'?'Vlna probíhá':game.state==='won'?'Sektor hotový':'Spustit vlnu <span>→</span>';$('next-label').textContent=game.state==='wave'?'ZBÝVÁ ZASTAVIT':'PŘÍŠTÍ VLNA';
 if(game.state==='wave')$('next-enemies').textContent=`${game.enemies.length+game.queue.length} lodí`;
 else if(game.state==='build'){const counts={};for(const t of wavePlan(game.index,game.wave+1))counts[t]=(counts[t]||0)+1;$('next-enemies').textContent=Object.entries(counts).map(([t,n])=>`${n}× ${ENEMIES[t].name.toLowerCase()}`).join(' · ');}else $('next-enemies').textContent='—';
 document.querySelectorAll('[data-tower]').forEach(b=>{b.classList.toggle('selected',blueprint===b.dataset.tower);b.classList.toggle('unaffordable',game.money<TYPES[b.dataset.tower].cost);b.setAttribute('aria-pressed',String(blueprint===b.dataset.tower));});
 const t=game.towerAt(selected),type=t?.type||blueprint,s=type?stats(t||{type,level:1}):null;
 $('cancel-selection').classList.toggle('hidden',selected<0&&!blueprint);$('tower-stats').classList.toggle('hidden',!s);$('upgrade-actions').classList.toggle('hidden',!t);
 if(s){$('selection-label').textContent=t?`POSTAVENÁ VĚŽ / ÚROVEŇ ${t.level} ZE 3`:'PŘIPRAVENO KE STAVBĚ';$('selection-name').textContent=s.name;$('selection-desc').textContent=s.desc;$('tower-stats').innerHTML=`<div><b>${Math.round(s.damage)}</b><span>POŠKOZENÍ</span></div><div><b>${s.range} m</b><span>DOSTŘEL</span></div><div><b>${s.rate.toFixed(1)} s</b><span>INTERVAL</span></div>`;}else{$('selection-label').textContent=selected>=0?'VOLNÉ STAVEBNÍ MÍSTO':'TAKTICKÁ RADA';$('selection-name').textContent=selected>=0?`Plošina ${selected+1}`:'Využij terén.';$('selection-desc').textContent=selected>=0?'Vyber typ věže z arzenálu. Věž se hned postaví.':game.level.tip;}
 if(t){$('upgrade').textContent=t.level>=3?'Maximální úroveň':`Vylepšit na ${t.level+1} · ${upgradeCost(t)}`;$('upgrade').disabled=t.level>=3||game.money<upgradeCost(t)||paused;$('sell').textContent=`Prodat za ${Math.floor(t.invested*.7)} kreditů`;$('sell').disabled=paused;}
 $('build-hint').textContent=blueprint?`${TYPES[blueprint].name}: klikni na svítící stavební místo.`:'Vyber věž a pak svítící místo na mapě.';
}
function events(){for(const e of game.events){if(e.type==='build'){effects.push({...e,age:0,life:.6});tone(430,.1,.035);}if(e.type==='kill'){effects.push({...e,age:0,life:.6});if(game.kills%3===0)tone(75,.12,.025,'triangle',35);}if(e.type==='blast'){effects.push({...e,age:0,life:.45});tone(58,.18,.04,'triangle',30);}if(e.type==='beam'){effects.push({...e,age:0,life:e.frost?.2:.16});}if(e.type==='leak'){effects.push({...e,age:0,life:.7});notice(`Loď proplula! Maják −${e.harm}`,1.6,true);tone(140,.3,.05,'sawtooth',75);}if(e.type==='wave'){notice(`Vlna ${e.wave} / ${game.level.waves} připlouvá`,2.2);tone(330,.2,.04);}if(e.type==='clear'){notice(`Čistá voda. Bonus +${e.bonus} kreditů.`,3);tone(660,.25,.04);}if(e.type==='boss'){notice('DREADNOUGHT NA DOHLED',3,true);tone(100,.7,.04,'sawtooth',60);}if(e.type==='end')end(e.won,e.stars);}game.events.length=0;}
function resize(){if(screen!=='battle')return;const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;viewW=r.width;viewH=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(viewW*dpr);canvas.height=Math.round(viewH*dpr);mapScale=Math.min(viewW/W,viewH/H);mapX=(viewW-W*mapScale)/2;mapY=(viewH-H*mapScale)/2;ctx.setTransform(dpr,0,0,dpr,0,0);}
new ResizeObserver(resize).observe(canvas);
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-mapX)/mapScale,y:(e.clientY-r.top-mapY)/mapScale};}
function nearest(p,threshold=43){let best=-1,d=Infinity;game.level.pads.forEach(([x,y],i)=>{const n=Math.hypot(x-p.x,y-p.y);if(n<d&&n<threshold){d=n;best=i;}});return best;}
canvas.addEventListener('pointermove',e=>{hover=nearest(point(e));});canvas.addEventListener('pointerleave',()=>hover=-1);canvas.addEventListener('pointerup',e=>{if(screen!=='battle'||paused)return;const i=nearest(point(e),e.pointerType==='touch'?Math.max(43,22/mapScale):43);if(i>=0)selectPad(i);else clearSelection();canvas.focus({preventScroll:true});});
window.addEventListener('keydown',e=>{if(screen!=='battle'||e.ctrlKey||e.metaKey||e.altKey||e.isComposing)return;const key=e.key||e.code;if($('modal').open){if((key==='p'||key==='P')&&!e.repeat&&paused){e.preventDefault();resume();}return;}if(e.target.closest?.('input,textarea,select'))return;
 if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key)){e.preventDefault();const [dx,dy]=key==='ArrowLeft'?[-1,0]:key==='ArrowRight'?[1,0]:key==='ArrowUp'?[0,-1]:[0,1];if(selected<0)selected=0;else{const [x,y]=game.level.pads[selected];const choices=game.level.pads.map(([xx,yy],i)=>({i,forward:(xx-x)*dx+(yy-y)*dy,side:Math.abs((xx-x)*dy-(yy-y)*dx),d:Math.hypot(xx-x,yy-y)})).filter(v=>v.forward>5).sort((a,b)=>(a.d+a.side*1.5)-(b.d+b.side*1.5));if(choices.length)selected=choices[0].i;}canvas.focus({preventScroll:true});syncUI();return;}
 if(e.repeat)return;
 if(['1','2','3','4'].includes(key)){e.preventDefault();chooseType(typeKeys[Number(key)-1]);}
 else if(key==='Enter'&&e.target===canvas&&selected>=0){e.preventDefault();selectPad(selected);}
 else if((key===' '||key==='Space')&&e.target===canvas){e.preventDefault();$('send-wave').click();}
 else if(key.toLowerCase()==='u'&&selected>=0){e.preventDefault();$('upgrade').click();}
 else if(key.toLowerCase()==='p'){e.preventDefault();pause();}
 else if(key==='Escape'){e.preventDefault();if(blueprint||selected>=0)clearSelection();else pause();}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='battle'&&!paused)pause();});window.addEventListener('blur',()=>{if(screen==='battle'&&game.state==='wave'&&!paused)pause();});
function draw(){ctx.clearRect(0,0,viewW,viewH);ctx.save();ctx.translate(mapX,mapY);ctx.scale(mapScale,mapScale);
 for(const points of game.level.paths){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#051923c4';ctx.lineWidth=36;ctx.stroke();ctx.strokeStyle='#d0b99435';ctx.lineWidth=30;ctx.stroke();ctx.strokeStyle='#dfc79f65';ctx.lineWidth=1.5;ctx.setLineDash([5,10]);ctx.lineDashOffset=reduced?0:-clock*9;ctx.stroke();ctx.setLineDash([]);}
 for(const path of game.paths){for(let d=90;d<path.length-30;d+=160){const p=onPath(path,d);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.beginPath();ctx.moveTo(-5,-5);ctx.lineTo(2,0);ctx.lineTo(-5,5);ctx.strokeStyle='#e9d8b680';ctx.lineWidth=1.5;ctx.stroke();ctx.restore();}}
 const active=selected>=0?selected:hover,t=game.towerAt(active),type=t?.type||blueprint;
 if(active>=0&&type){const [x,y]=game.level.pads[active],s=stats(t||{type,level:1});circle(ctx,x,y,s.range,s.color+'0c',s.color+'57',1);}
 game.level.pads.forEach(([x,y],i)=>{const tower=game.towerAt(i),isSelected=i===selected||i===hover;circle(ctx,x,y,27,'#061f2be8',isSelected?'#d4ffe4':tower?'#7eab9266':'#a2d2b570',isSelected?2:1);if(!tower){ctx.strokeStyle=isSelected?'#b8ffd9':'#99ccb966';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x-7,y);ctx.lineTo(x+7,y);ctx.moveTo(x,y-7);ctx.lineTo(x,y+7);ctx.stroke();if(isSelected){ctx.fillStyle='#bedbca';ctx.font='12px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillText(String(i+1),x,y+43);}}});
 const baseX=931,baseY=300;circle(ctx,baseX,baseY,40,'#ffd1920c','#ffd19244',1);circle(ctx,baseX,baseY,29,'#20383a','#ffd192',2);ctx.beginPath();ctx.arc(baseX,baseY,35,-Math.PI/2,-Math.PI/2+Math.PI*2*game.lives/20);ctx.strokeStyle=game.lives<8?'#ff8094':'#ffd192';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#ffd192';ctx.font='25px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('Ⅱ',baseX,baseY);ctx.textBaseline='alphabetic';ctx.font='10px "DM Sans",sans-serif';ctx.fillText('MAJÁK',baseX,baseY+53);
 for(const t of game.towers){turret(ctx,t.x,t.y,t.type,t.angle,t.level);if(t.cool>stats(t).rate-.075){circle(ctx,t.x+Math.cos(t.angle)*28,t.y+Math.sin(t.angle)*28,7,TYPES[t.type].color+'b0');}}
 for(const e of game.enemies){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.angle);if(!reduced){ctx.beginPath();ctx.moveTo(-e.size,e.size*.6);ctx.lineTo(-e.size-18,e.size);ctx.moveTo(-e.size,-e.size*.6);ctx.lineTo(-e.size-18,-e.size);ctx.strokeStyle='#d0eee51f';ctx.lineWidth=2;ctx.stroke();}ctx.shadowColor='#000a';ctx.shadowBlur=5;ctx.shadowOffsetY=4;ctx.beginPath();ctx.moveTo(e.size*1.6,0);ctx.lineTo(e.size*.6,-e.size*.7);ctx.lineTo(-e.size*1.1,-e.size*.7);ctx.lineTo(-e.size*.8,0);ctx.lineTo(-e.size*1.1,e.size*.7);ctx.lineTo(e.size*.6,e.size*.7);ctx.closePath();ctx.fillStyle=e.flash>0?'#fff0df':e.color;ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle=e.armor?'#ffd6e5':'#ffffff55';ctx.lineWidth=e.armor?2:1;ctx.stroke();ctx.fillStyle='#22323b';ctx.fillRect(-e.size*.6,-e.size*.4,e.size,e.size*.8);ctx.fillStyle=e.color;ctx.fillRect(-e.size*.25,-e.size*.15,e.size*.65,e.size*.3);ctx.restore();if(e.slow>0){circle(ctx,e.x,e.y,e.size+8,null,'#80dfff88',2);}if(e.hp<e.maxHp||e.type==='boss'){const w=e.type==='boss'?64:30;ctx.fillStyle='#091e27';ctx.fillRect(e.x-w/2,e.y-e.size-14,w,4);ctx.fillStyle=e.type==='boss'?'#ff8094':e.slow>0?'#80dfff':'#dcdca0';ctx.fillRect(e.x-w/2,e.y-e.size-14,w*Math.max(0,e.hp/e.maxHp),4);}if(e.type==='boss'){ctx.font='bold 10px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle='#ffb4c1';ctx.fillText('DREADNOUGHT',e.x,e.y-49);}}
 for(const p of game.projectiles){const q=Math.min(1,p.age/p.duration),x=p.ox+(p.tx-p.ox)*q,y=p.oy+(p.ty-p.oy)*q-(p.type==='mortar'?Math.sin(q*Math.PI)*65:0);ctx.beginPath();ctx.moveTo(x-(p.tx-p.ox)*.035,y-(p.ty-p.oy)*.035);ctx.lineTo(x,y);ctx.strokeStyle=p.color;ctx.lineWidth=p.type==='mortar'?4:2;ctx.stroke();circle(ctx,x,y,p.type==='mortar'?4:2.5,'#fff0d2');if(p.type==='mortar')circle(ctx,p.tx,p.ty,12,null,'#ffd19260',1);}
 for(const e of effects){const q=e.age/e.life;ctx.globalAlpha=1-q;if(e.type==='beam'){ctx.beginPath();ctx.moveTo(e.x,e.y);const dx=e.tx-e.x,dy=e.ty-e.y,n=Math.hypot(dx,dy)||1;for(let i=1;i<6;i++){const wobble=e.frost?0:Math.sin(i*6.7+e.age*70)*9;ctx.lineTo(e.x+dx*i/6-dy/n*wobble,e.y+dy*i/6+dx/n*wobble);}ctx.lineTo(e.tx,e.ty);ctx.strokeStyle=e.color;ctx.lineWidth=e.frost?2:3;ctx.stroke();circle(ctx,e.tx,e.ty,8,null,e.color,2);}else if(e.type==='blast'){circle(ctx,e.x,e.y,65*q,e.color+'18',e.color,2);circle(ctx,e.x,e.y,18*(1-q),'#fff3dabb');}else if(e.type==='build'){circle(ctx,e.x,e.y,24+q*25,null,e.color,2);}else if(e.type==='leak'){circle(ctx,e.x,e.y,15+q*65,null,'#ff8094',3);}else if(e.type==='kill'){for(let i=0;i<7;i++){const a=i*2.4;circle(ctx,e.x+Math.cos(a)*q*35,e.y+Math.sin(a)*q*35,2.8*(1-q),e.color);}ctx.fillStyle='#b8ffd9';ctx.font='bold 12px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillText('+'+e.bounty,e.x,e.y-14-q*25);}}ctx.globalAlpha=1;ctx.restore();}
function frame(ms){const dt=Math.min((ms-last)/1000||0,.05);last=ms;clock+=dt;if(screen==='battle'){if(!paused){for(let i=0;i<speed;i++){game.step(dt);events();if(['won','lost'].includes(game.state))break;}for(const e of effects)e.age+=dt;effects=effects.filter(e=>e.age<e.life).slice(-180);noticeTime-=dt;if(noticeTime<=0)$('notice').classList.remove('show');}uiClock+=dt;if(uiClock>.15){syncUI();uiClock=0;}draw();}requestAnimationFrame(frame);}
makeTowerCards();drawCampaign();requestAnimationFrame(frame);
